// Copyright 2026- The sacloud/service-endpoint-gateway-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"github.com/go-faster/jx"
)

// SetFake set fake values.
func (s *ModelsApplianceAppliance) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Class.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description = "string"
		}
	}
	{
		{
			s.Plan.SetFake()
		}
	}
	{
		{
			s.Settings.SetFake()
		}
	}
	{
		{
			s.SettingsHash.SetFake()
		}
	}
	{
		{
			s.Remark.SetFake()
		}
	}
	{
		{
			s.Availability.SetFake()
		}
	}
	{
		{
			s.Instance.SetFake()
		}
	}
	{
		{
			s.Disk.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
	{
		{
			s.Generation = int32(0)
		}
	}
	{
		{
			s.CreatedAt = "string"
		}
	}
	{
		{
			s.Icon = []byte("null")
		}
	}
	{
		{
			s.Switch.SetFake()
		}
	}
	{
		{
			s.Interfaces = nil
			for i := 0; i < 0; i++ {
				var elem ModelsNetworkInterface
				{
					elem.SetFake()
				}
				s.Interfaces = append(s.Interfaces, elem)
			}
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem jx.Raw
				{
					elem = []byte("null")
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ModelsApplianceApplianceApplyResponse) SetFake() {
	{
		{
			s.Success = true
		}
	}
	{
		{
			s.ReturnCode = int32(0)
		}
	}
	{
		{
			s.ResponseHeaders.SetFake()
		}
	}
	{
		{
			s.Out.SetFake()
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *ModelsApplianceApplianceApplyResponseResponseHeaders) SetFake() {
	{
		{
			s.Status = "string"
		}
	}
	{
		{
			s.Cause.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsApplianceApplianceAvailability) SetFake() {
	*s = ModelsApplianceApplianceAvailabilityAvailable
}

// SetFake set fake values.
func (s *ModelsApplianceApplianceClass) SetFake() {
	*s = ModelsApplianceApplianceClassServiceendpointgateway
}

// SetFake set fake values.
func (s *ModelsApplianceApplianceCreateBody) SetFake() {
	{
		{
			s.Class.SetFake()
		}
	}
	{
		{
			s.Plan.SetFake()
		}
	}
	{
		{
			s.Remark.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsApplianceApplianceCreateBodyClass) SetFake() {
	*s = ModelsApplianceApplianceCreateBodyClassServiceendpointgateway
}

// SetFake set fake values.
func (s *ModelsApplianceApplianceCreateRequest) SetFake() {
	{
		{
			s.Appliance.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsApplianceApplianceCreateResponseBody) SetFake() {
	{
		{
			s.Appliance.SetFake()
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *ModelsApplianceApplianceGetInterfaceResponseBody) SetFake() {
	{
		{
			s.Interface.SetFake()
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *ModelsApplianceApplianceGetResponseBody) SetFake() {
	{
		{
			s.Appliance.SetFake()
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *ModelsApplianceApplianceListResponseBody) SetFake() {
	{
		{
			s.From = int32(0)
		}
	}
	{
		{
			s.Count = int32(0)
		}
	}
	{
		{
			s.Total = int32(0)
		}
	}
	{
		{
			s.Appliances = nil
			for i := 0; i < 0; i++ {
				var elem ModelsApplianceAppliance
				{
					elem.SetFake()
				}
				s.Appliances = append(s.Appliances, elem)
			}
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *ModelsApplianceApplianceServiceClass) SetFake() {
	*s = ModelsApplianceApplianceServiceClassCloudApplianceServiceendpointgateway1
}

// SetFake set fake values.
func (s *ModelsApplianceApplianceUpdateBody) SetFake() {
	{
		{
			s.Settings.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsApplianceApplianceUpdateRequest) SetFake() {
	{
		{
			s.Appliance.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsCommonDefaultErrorResponseBody) SetFake() {
	{
		{
			s.IsFatal.SetFake()
		}
	}
	{
		{
			s.Serial.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.ErrorCode.SetFake()
		}
	}
	{
		{
			s.ErrorMsg.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsDiskDedicatedStorageContract) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsDiskDisk) SetFake() {
	{
		{
			s.EncryptionAlgorithm.SetFake()
		}
	}
	{
		{
			s.EncryptionKey.SetFake()
		}
	}
	{
		{
			s.DedicatedStorageContract.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsDiskEncryptionKey) SetFake() {
	{
		{
			s.KMSKeyID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsInstanceHostInfo) SetFake() {
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.InfoURL.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsInstanceInstance) SetFake() {
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.StatusChangedAt.SetFake()
		}
	}
	{
		{
			s.Host.SetFake()
		}
	}
	{
		{
			s.Hosts = nil
			for i := 0; i < 0; i++ {
				var elem ModelsInstanceHostInfo
				{
					elem.SetFake()
				}
				s.Hosts = append(s.Hosts, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ModelsInstanceInstanceForPower) SetFake() {
	{
		{
			s.Status.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsInstanceInstanceForPowerStatus) SetFake() {
	*s = ModelsInstanceInstanceForPowerStatusUp
}

// SetFake set fake values.
func (s *ModelsInstanceInstanceStatus) SetFake() {
	*s = ModelsInstanceInstanceStatusUp
}

// SetFake set fake values.
func (s *ModelsNetworkInterface) SetFake() {
	{
		{
			s.IPAddress.SetFake()
		}
	}
	{
		{
			s.UserIPAddress.SetFake()
		}
	}
	{
		{
			s.HostName.SetFake()
		}
	}
	{
		{
			s.Switch.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsNetworkInterfaceSwitch) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Scope.SetFake()
		}
	}
	{
		{
			s.Subnet.SetFake()
		}
	}
	{
		{
			s.UserSubnet.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsNetworkInterfaceSwitchScope) SetFake() {
	*s = ModelsNetworkInterfaceSwitchScopeUser
}

// SetFake set fake values.
func (s *ModelsNetworkInternetInfo) SetFake() {
	{
		{
			s.BandWidthMbps.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsNetworkRegion) SetFake() {
	{
		{
			s.ID = int32(0)
		}
	}
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *ModelsNetworkSimpleInterface) SetFake() {
	{
		{
			s.IPAddress.SetFake()
		}
	}
	{
		{
			s.UserIPAddress.SetFake()
		}
	}
	{
		{
			s.Switch.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsNetworkSimpleInterfaceSwitch) SetFake() {
	{
		{
			s.Scope.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsNetworkSimpleInterfaceSwitchScope) SetFake() {
	*s = ModelsNetworkSimpleInterfaceSwitchScopeUser
}

// SetFake set fake values.
func (s *ModelsNetworkSubnet) SetFake() {
	{
		{
			s.NetworkAddress = "string"
		}
	}
	{
		{
			s.NetworkMaskLen = int32(0)
		}
	}
	{
		{
			s.DefaultRoute.SetFake()
		}
	}
	{
		{
			s.Internet.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsNetworkSwitch) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Internet.SetFake()
		}
	}
	{
		{
			s.Scope.SetFake()
		}
	}
	{
		{
			s.Availability.SetFake()
		}
	}
	{
		{
			s.Zone.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsNetworkSwitchAvailability) SetFake() {
	*s = ModelsNetworkSwitchAvailabilityAvailable
}

// SetFake set fake values.
func (s *ModelsNetworkSwitchScope) SetFake() {
	*s = ModelsNetworkSwitchScopeUser
}

// SetFake set fake values.
func (s *ModelsNetworkUserSubnet) SetFake() {
	{
		{
			s.DefaultRoute.SetFake()
		}
	}
	{
		{
			s.NetworkMaskLen = int32(0)
		}
	}
}

// SetFake set fake values.
func (s *ModelsNetworkZone) SetFake() {
	{
		{
			s.ID = int32(0)
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Region.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsPlanPlan) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsPlanPlanID) SetFake() {
	*s = ModelsPlanPlanID1
}

// SetFake set fake values.
func (s *ModelsPowerApplianceDeletePowerStatusRequest) SetFake() {
	{
		{
			s.Force = true
		}
	}
}

// SetFake set fake values.
func (s *ModelsPowerApplianceGetPowerStatusResponseBody) SetFake() {
	{
		{
			s.Instance.SetFake()
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *ModelsPowerApplianceUpdatePowerStatusResponseBody) SetFake() {
	{
		{
			s.Success.SetFake()
		}
	}
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *ModelsPowerApplianceUpdatePowerStatusResponseBodySuccess) SetFake() {
	var variant bool

	{
		variant = true
	}
	s.SetBool(variant)
}

// SetFake set fake values.
func (s *ModelsRemarkApplianceCreateRemark) SetFake() {
	{
		{
			s.Switch.SetFake()
		}
	}
	{
		{
			s.Network.SetFake()
		}
	}
	{
		{
			s.Servers = nil
			for i := 0; i < 0; i++ {
				var elem ModelsRemarkServerRemark
				{
					elem.SetFake()
				}
				s.Servers = append(s.Servers, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ModelsRemarkApplianceRemark) SetFake() {
	{
		{
			s.Switch.SetFake()
		}
	}
	{
		{
			s.Network.SetFake()
		}
	}
	{
		{
			s.Servers = nil
			for i := 0; i < 0; i++ {
				var elem ModelsRemarkServerRemark
				{
					elem.SetFake()
				}
				s.Servers = append(s.Servers, elem)
			}
		}
	}
	{
		{
			s.Zone.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsRemarkNetworkRemark) SetFake() {
	{
		{
			s.NetworkMaskLen = int32(0)
		}
	}
}

// SetFake set fake values.
func (s *ModelsRemarkServerRemark) SetFake() {
	{
		{
			s.IPAddress = "string"
		}
	}
}

// SetFake set fake values.
func (s *ModelsRemarkSwitchRemark) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
}

// SetFake set fake values.
func (s *ModelsRemarkZoneRemark) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
}

// SetFake set fake values.
func (s *ModelsSettingsApplianceSettings) SetFake() {
	{
		{
			s.ServiceEndpointGateway.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsSettingsDNSForwardingSettings) SetFake() {
	{
		{
			s.Enabled.SetFake()
		}
	}
	{
		{
			s.PrivateHostedZone = "string"
		}
	}
	{
		{
			s.UpstreamDNS1 = "string"
		}
	}
	{
		{
			s.UpstreamDNS2 = "string"
		}
	}
}

// SetFake set fake values.
func (s *ModelsSettingsDNSForwardingSettingsEnabled) SetFake() {
	*s = ModelsSettingsDNSForwardingSettingsEnabledTrue
}

// SetFake set fake values.
func (s *ModelsSettingsEnabledService) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.Config.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsSettingsEnabledServiceType) SetFake() {
	*s = ModelsSettingsEnabledServiceTypeObjectStorage
}

// SetFake set fake values.
func (s *ModelsSettingsMonitoringSuiteSettings) SetFake() {
	{
		{
			s.Enabled.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsSettingsMonitoringSuiteSettingsEnabled) SetFake() {
	*s = ModelsSettingsMonitoringSuiteSettingsEnabledTrue
}

// SetFake set fake values.
func (s *ModelsSettingsServiceConfig) SetFake() {
	{
		{
			s.Endpoints = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Endpoints = append(s.Endpoints, elem)
			}
		}
	}
	{
		{
			s.Mode.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelsSettingsServiceConfigMode) SetFake() {
	*s = ModelsSettingsServiceConfigModeManaged
}

// SetFake set fake values.
func (s *ModelsSettingsServiceEndpointGatewaySettings) SetFake() {
	{
		{
			s.EnabledServices = nil
			for i := 0; i < 0; i++ {
				var elem ModelsSettingsEnabledService
				{
					elem.SetFake()
				}
				s.EnabledServices = append(s.EnabledServices, elem)
			}
		}
	}
	{
		{
			s.MonitoringSuite.SetFake()
		}
	}
	{
		{
			s.DNSForwarding.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NilInt32) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilModelsDiskDedicatedStorageContract) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilModelsDiskDisk) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilModelsDiskEncryptionKey) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilModelsNetworkInternetInfo) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilModelsNetworkSubnet) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilModelsNetworkUserSubnet) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilModelsPowerApplianceUpdatePowerStatusResponseBodySuccess) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilModelsRemarkApplianceRemark) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilModelsSettingsApplianceSettings) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NilString) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *OptBool) SetFake() {
	var elem bool
	{
		elem = true
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptModelsApplianceApplianceUpdateRequest) SetFake() {
	var elem ModelsApplianceApplianceUpdateRequest
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptModelsPowerApplianceDeletePowerStatusRequest) SetFake() {
	var elem ModelsPowerApplianceDeletePowerStatusRequest
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptModelsSettingsDNSForwardingSettings) SetFake() {
	var elem ModelsSettingsDNSForwardingSettings
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptModelsSettingsMonitoringSuiteSettings) SetFake() {
	var elem ModelsSettingsMonitoringSuiteSettings
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptModelsSettingsServiceConfigMode) SetFake() {
	var elem ModelsSettingsServiceConfigMode
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNilModelsInstanceHostInfo) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilModelsInstanceInstanceStatus) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilString) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptString) SetFake() {
	var elem string
	{
		elem = "string"
	}
	s.SetTo(elem)
}
