// Copyright 2022-2026 The sacloud/service-endpoint-gateway-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by ogen, DO NOT EDIT.

package v1

// SegApplyParams is parameters of seg_apply operation.
type SegApplyParams struct {
	ApplianceID string
}

// SegDeleteParams is parameters of seg_delete operation.
type SegDeleteParams struct {
	ApplianceID string
}

// SegGetParams is parameters of seg_get operation.
type SegGetParams struct {
	ApplianceID string
}

// SegInterfaceGetInterfaceParams is parameters of segInterface_getInterface operation.
type SegInterfaceGetInterfaceParams struct {
	ApplianceID string
	InterfaceID string
}

// SegStatusDeletePowerStatusParams is parameters of segStatus_deletePowerStatus operation.
type SegStatusDeletePowerStatusParams struct {
	ApplianceID string
}

// SegStatusGetPowerStatusParams is parameters of segStatus_getPowerStatus operation.
type SegStatusGetPowerStatusParams struct {
	ApplianceID string
}

// SegStatusResetPowerStatusParams is parameters of segStatus_resetPowerStatus operation.
type SegStatusResetPowerStatusParams struct {
	ApplianceID string
}

// SegStatusUpdatePowerStatusParams is parameters of segStatus_updatePowerStatus operation.
type SegStatusUpdatePowerStatusParams struct {
	ApplianceID string
}

// SegUpdateParams is parameters of seg_update operation.
type SegUpdateParams struct {
	ApplianceID string
}
