// Copyright 2026- The sacloud/service-endpoint-gateway-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"
	"net/url"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// SegApply invokes seg_apply operation.
	//
	// 指定したサービスエンドポイントゲートウェイの情報を適用します。.
	//
	// PUT /appliance/{applianceID}/config
	SegApply(ctx context.Context, request OptModelsApplianceApplianceUpdateRequest, params SegApplyParams) (*ModelsApplianceApplianceApplyResponse, error)
	// SegCreate invokes seg_create operation.
	//
	// 指定したサービスエンドポイントゲートウェイを作成します。.
	//
	// POST /appliance
	SegCreate(ctx context.Context, request *ModelsApplianceApplianceCreateRequest) (*ModelsApplianceApplianceCreateResponseBody, error)
	// SegDelete invokes seg_delete operation.
	//
	// 指定したサービスエンドポイントゲートウェイを削除します。.
	//
	// DELETE /appliance/{applianceID}
	SegDelete(ctx context.Context, params SegDeleteParams) (*ModelsApplianceApplianceGetResponseBody, error)
	// SegGet invokes seg_get operation.
	//
	// 指定したサービスエンドポイントゲートウェイの情報を取得します。.
	//
	// GET /appliance/{applianceID}
	SegGet(ctx context.Context, params SegGetParams) (*ModelsApplianceApplianceGetResponseBody, error)
	// SegInterfaceGetInterface invokes segInterface_getInterface operation.
	//
	// 指定したサービスエンドポイントゲートウェイのインターフェース情報を取得します。.
	//
	// GET /appliance/{applianceID}/interface/{interfaceID}
	SegInterfaceGetInterface(ctx context.Context, params SegInterfaceGetInterfaceParams) (*ModelsApplianceApplianceGetInterfaceResponseBody, error)
	// SegList invokes seg_list operation.
	//
	// サービスエンドポイントゲートウェイの一覧を取得します。.
	//
	// GET /appliance
	SegList(ctx context.Context) (*ModelsApplianceApplianceListResponseBody, error)
	// SegStatusDeletePowerStatus invokes segStatus_deletePowerStatus operation.
	//
	// 指定したサービスエンドポイントゲートウェイを停止します。.
	//
	// DELETE /appliance/{applianceID}/power
	SegStatusDeletePowerStatus(ctx context.Context, request OptModelsPowerApplianceDeletePowerStatusRequest, params SegStatusDeletePowerStatusParams) (*ModelsPowerApplianceUpdatePowerStatusResponseBody, error)
	// SegStatusGetPowerStatus invokes segStatus_getPowerStatus operation.
	//
	// 指定したサービスエンドポイントゲートウェイの起動状態を取得します。.
	//
	// GET /appliance/{applianceID}/power
	SegStatusGetPowerStatus(ctx context.Context, params SegStatusGetPowerStatusParams) (*ModelsPowerApplianceGetPowerStatusResponseBody, error)
	// SegStatusResetPowerStatus invokes segStatus_resetPowerStatus operation.
	//
	// 指定したサービスエンドポイントゲートウェイの起動状態をリセットします。.
	//
	// PUT /appliance/{applianceID}/reset
	SegStatusResetPowerStatus(ctx context.Context, params SegStatusResetPowerStatusParams) (*ModelsPowerApplianceUpdatePowerStatusResponseBody, error)
	// SegStatusUpdatePowerStatus invokes segStatus_updatePowerStatus operation.
	//
	// 指定したサービスエンドポイントゲートウェイを起動します。.
	//
	// PUT /appliance/{applianceID}/power
	SegStatusUpdatePowerStatus(ctx context.Context, params SegStatusUpdatePowerStatusParams) (*ModelsPowerApplianceUpdatePowerStatusResponseBody, error)
	// SegUpdate invokes seg_update operation.
	//
	// 指定したサービスエンドポイントゲートウェイの情報を更新します。
	// 更新後には、別途「サービスエンドポイントゲートウェイ適用API」を呼び出して設定を反映する必要があります。.
	//
	// PUT /appliance/{applianceID}
	SegUpdate(ctx context.Context, request *ModelsApplianceApplianceUpdateRequest, params SegUpdateParams) (*ModelsApplianceApplianceGetResponseBody, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// SegApply invokes seg_apply operation.
//
// 指定したサービスエンドポイントゲートウェイの情報を適用します。.
//
// PUT /appliance/{applianceID}/config
func (c *Client) SegApply(ctx context.Context, request OptModelsApplianceApplianceUpdateRequest, params SegApplyParams) (*ModelsApplianceApplianceApplyResponse, error) {
	res, err := c.sendSegApply(ctx, request, params)
	return res, err
}

func (c *Client) sendSegApply(ctx context.Context, request OptModelsApplianceApplianceUpdateRequest, params SegApplyParams) (res *ModelsApplianceApplianceApplyResponse, err error) {
	// Validate request before sending.
	if err := func() error {
		if value, ok := request.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/appliance/"
	{
		// Encode "applianceID" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "applianceID",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ApplianceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/config"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSegApplyRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeSegApplyResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SegCreate invokes seg_create operation.
//
// 指定したサービスエンドポイントゲートウェイを作成します。.
//
// POST /appliance
func (c *Client) SegCreate(ctx context.Context, request *ModelsApplianceApplianceCreateRequest) (*ModelsApplianceApplianceCreateResponseBody, error) {
	res, err := c.sendSegCreate(ctx, request)
	return res, err
}

func (c *Client) sendSegCreate(ctx context.Context, request *ModelsApplianceApplianceCreateRequest) (res *ModelsApplianceApplianceCreateResponseBody, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/appliance"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSegCreateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeSegCreateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SegDelete invokes seg_delete operation.
//
// 指定したサービスエンドポイントゲートウェイを削除します。.
//
// DELETE /appliance/{applianceID}
func (c *Client) SegDelete(ctx context.Context, params SegDeleteParams) (*ModelsApplianceApplianceGetResponseBody, error) {
	res, err := c.sendSegDelete(ctx, params)
	return res, err
}

func (c *Client) sendSegDelete(ctx context.Context, params SegDeleteParams) (res *ModelsApplianceApplianceGetResponseBody, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/appliance/"
	{
		// Encode "applianceID" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "applianceID",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ApplianceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeSegDeleteResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SegGet invokes seg_get operation.
//
// 指定したサービスエンドポイントゲートウェイの情報を取得します。.
//
// GET /appliance/{applianceID}
func (c *Client) SegGet(ctx context.Context, params SegGetParams) (*ModelsApplianceApplianceGetResponseBody, error) {
	res, err := c.sendSegGet(ctx, params)
	return res, err
}

func (c *Client) sendSegGet(ctx context.Context, params SegGetParams) (res *ModelsApplianceApplianceGetResponseBody, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/appliance/"
	{
		// Encode "applianceID" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "applianceID",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ApplianceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeSegGetResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SegInterfaceGetInterface invokes segInterface_getInterface operation.
//
// 指定したサービスエンドポイントゲートウェイのインターフェース情報を取得します。.
//
// GET /appliance/{applianceID}/interface/{interfaceID}
func (c *Client) SegInterfaceGetInterface(ctx context.Context, params SegInterfaceGetInterfaceParams) (*ModelsApplianceApplianceGetInterfaceResponseBody, error) {
	res, err := c.sendSegInterfaceGetInterface(ctx, params)
	return res, err
}

func (c *Client) sendSegInterfaceGetInterface(ctx context.Context, params SegInterfaceGetInterfaceParams) (res *ModelsApplianceApplianceGetInterfaceResponseBody, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [4]string
	pathParts[0] = "/appliance/"
	{
		// Encode "applianceID" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "applianceID",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ApplianceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/interface/"
	{
		// Encode "interfaceID" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "interfaceID",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.InterfaceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeSegInterfaceGetInterfaceResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SegList invokes seg_list operation.
//
// サービスエンドポイントゲートウェイの一覧を取得します。.
//
// GET /appliance
func (c *Client) SegList(ctx context.Context) (*ModelsApplianceApplianceListResponseBody, error) {
	res, err := c.sendSegList(ctx)
	return res, err
}

func (c *Client) sendSegList(ctx context.Context) (res *ModelsApplianceApplianceListResponseBody, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/appliance"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeSegListResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SegStatusDeletePowerStatus invokes segStatus_deletePowerStatus operation.
//
// 指定したサービスエンドポイントゲートウェイを停止します。.
//
// DELETE /appliance/{applianceID}/power
func (c *Client) SegStatusDeletePowerStatus(ctx context.Context, request OptModelsPowerApplianceDeletePowerStatusRequest, params SegStatusDeletePowerStatusParams) (*ModelsPowerApplianceUpdatePowerStatusResponseBody, error) {
	res, err := c.sendSegStatusDeletePowerStatus(ctx, request, params)
	return res, err
}

func (c *Client) sendSegStatusDeletePowerStatus(ctx context.Context, request OptModelsPowerApplianceDeletePowerStatusRequest, params SegStatusDeletePowerStatusParams) (res *ModelsPowerApplianceUpdatePowerStatusResponseBody, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/appliance/"
	{
		// Encode "applianceID" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "applianceID",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ApplianceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/power"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSegStatusDeletePowerStatusRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeSegStatusDeletePowerStatusResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SegStatusGetPowerStatus invokes segStatus_getPowerStatus operation.
//
// 指定したサービスエンドポイントゲートウェイの起動状態を取得します。.
//
// GET /appliance/{applianceID}/power
func (c *Client) SegStatusGetPowerStatus(ctx context.Context, params SegStatusGetPowerStatusParams) (*ModelsPowerApplianceGetPowerStatusResponseBody, error) {
	res, err := c.sendSegStatusGetPowerStatus(ctx, params)
	return res, err
}

func (c *Client) sendSegStatusGetPowerStatus(ctx context.Context, params SegStatusGetPowerStatusParams) (res *ModelsPowerApplianceGetPowerStatusResponseBody, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/appliance/"
	{
		// Encode "applianceID" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "applianceID",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ApplianceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/power"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeSegStatusGetPowerStatusResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SegStatusResetPowerStatus invokes segStatus_resetPowerStatus operation.
//
// 指定したサービスエンドポイントゲートウェイの起動状態をリセットします。.
//
// PUT /appliance/{applianceID}/reset
func (c *Client) SegStatusResetPowerStatus(ctx context.Context, params SegStatusResetPowerStatusParams) (*ModelsPowerApplianceUpdatePowerStatusResponseBody, error) {
	res, err := c.sendSegStatusResetPowerStatus(ctx, params)
	return res, err
}

func (c *Client) sendSegStatusResetPowerStatus(ctx context.Context, params SegStatusResetPowerStatusParams) (res *ModelsPowerApplianceUpdatePowerStatusResponseBody, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/appliance/"
	{
		// Encode "applianceID" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "applianceID",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ApplianceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/reset"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeSegStatusResetPowerStatusResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SegStatusUpdatePowerStatus invokes segStatus_updatePowerStatus operation.
//
// 指定したサービスエンドポイントゲートウェイを起動します。.
//
// PUT /appliance/{applianceID}/power
func (c *Client) SegStatusUpdatePowerStatus(ctx context.Context, params SegStatusUpdatePowerStatusParams) (*ModelsPowerApplianceUpdatePowerStatusResponseBody, error) {
	res, err := c.sendSegStatusUpdatePowerStatus(ctx, params)
	return res, err
}

func (c *Client) sendSegStatusUpdatePowerStatus(ctx context.Context, params SegStatusUpdatePowerStatusParams) (res *ModelsPowerApplianceUpdatePowerStatusResponseBody, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/appliance/"
	{
		// Encode "applianceID" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "applianceID",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ApplianceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/power"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeSegStatusUpdatePowerStatusResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SegUpdate invokes seg_update operation.
//
// 指定したサービスエンドポイントゲートウェイの情報を更新します。
// 更新後には、別途「サービスエンドポイントゲートウェイ適用API」を呼び出して設定を反映する必要があります。.
//
// PUT /appliance/{applianceID}
func (c *Client) SegUpdate(ctx context.Context, request *ModelsApplianceApplianceUpdateRequest, params SegUpdateParams) (*ModelsApplianceApplianceGetResponseBody, error) {
	res, err := c.sendSegUpdate(ctx, request, params)
	return res, err
}

func (c *Client) sendSegUpdate(ctx context.Context, request *ModelsApplianceApplianceUpdateRequest, params SegUpdateParams) (res *ModelsApplianceApplianceGetResponseBody, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/appliance/"
	{
		// Encode "applianceID" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "applianceID",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ApplianceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSegUpdateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeSegUpdateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
